/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.actions;

import hibernate.client.ClientDAOInterface;
import hibernate.config.NMMUMobileDAOManager;
import hibernate.security.SecurityDAOInterface;
import hibernate.user.UserDAOInterface;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import tools.AMSException;

import common.security.RoleENT;
import common.security.RoleLST;
import common.user.UserENT;

/**
 * MyEclipse Struts Creation date: 09-21-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="reqCode" validate="true"
 * @struts.action-forward name="list" path="/jsp/farsi/news/newsList.jsp"
 */
public class UserAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ActionForward af = null;
		String reqCode = request.getParameter("reqCode");
		String success = "";
		String error = "";
		if (reqCode.equalsIgnoreCase("userRoleView")) {
			try {
				UserENT u = getUserDAO().getUserENT(
						new UserENT("", Integer.parseInt(request
								.getParameter("userID"))));
				request.setAttribute("userENT", u);
				RoleLST roleLST = new RoleLST();
				String searchKey = "";
				if(request.getParameter("searchKey")!=null)
					searchKey = request.getParameter("searchKey");
				roleLST.setSearchRole(new RoleENT(0, searchKey, 0, "", ""));
				roleLST.setPageSize(400);
				RoleLST roles = getSecurityDAO().getRolesList(roleLST);
				request.setAttribute("userRoles", getUserDAO().getAllRolesUser(u.getUserID()));
				request.setAttribute("rolesList", roles);
				return mapping.findForward("userRole");
			} catch (NumberFormatException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (AMSException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return af;
	}

	private int getClientID() {
		// TODO Auto-generated method stub
		return 0;
	}

	private static SecurityDAOInterface getSecurityDAO() {
		return NMMUMobileDAOManager.getSecuirtyDAOInterface();
	}

	private static UserDAOInterface getUserDAO() {
		return NMMUMobileDAOManager.getUserDAOInterface();
	}
}