package common.location;

// Generated Apr 11, 2017 5:12:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigInteger;
import java.util.ArrayList;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
public class LocationENTQRBarcode {

	public long id;
	public String t;// type
	public String n;// Name
	public String g;// gps or image uri
	public LocationENTQRBarcode p; // parent

	public LocationENTQRBarcode(long id, String t, String n, String g,
			LocationENTQRBarcode p) {
		super();
		this.id = id;
		this.t = t;
		this.n = n;
		this.g = g;
		this.p = p;
	}
	
	public LocationENTQRBarcode(long id) {
		super();
		this.id = id;
	}
	
	public LocationENTQRBarcode() {
		super();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getT() {
		return t;
	}

	public void setT(String t) {
		this.t = t;
	}

	public String getN() {
		return n;
	}

	public void setN(String n) {
		this.n = n;
	}

	public String getG() {
		return g;
	}

	public void setG(String g) {
		this.g = g;
	}


	public LocationENTQRBarcode getP() {
		return p;
	}

	public void setP(LocationENTQRBarcode p) {
		this.p = p;
	}

}
