package common.location;

// Generated Apr 11, 2017 5:12:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "nmmumobile")
public class LocationENT implements java.io.Serializable {

	private long locationID;
	private int userID;
	private int country;
	private String state;
	private String address;
	private String postBox;
	private String tel;
	private String fax;
	private String email;
	private String street;
	private String area;
	private String cell;
	private String gps;
	private String locationName;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "location_id", unique = true, nullable = false)
	public long getLocationID() {
		return this.locationID;
	}

	public void setLocationID(long locationID) {
		this.locationID = locationID;
	}

	@Column(name = "user_id", nullable = true)
	public int getUserID() {
		return this.userID;
	}

	public void setUserID(int userID) {
		this.userID = userID;
	}

	@Column(name = "country", nullable = false)
	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	@Column(name = "state", nullable = false, length = 2000)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "address", nullable = false, length = 2000)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "post_box", nullable = false, length = 2000)
	public String getPostBox() {
		return this.postBox;
	}

	public void setPostBox(String postBox) {
		this.postBox = postBox;
	}

	@Column(name = "tel", nullable = false, length = 2000)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "fax", nullable = false, length = 2000)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", nullable = false, length = 2000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "street", nullable = false, length = 200)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "area", nullable = false, length = 200)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "cell", nullable = false, length = 2000)
	public String getCell() {
		return this.cell;
	}

	public void setCell(String cell) {
		this.cell = cell;
	}

	@Column(name = "gps", nullable = false, length = 200)
	public String getGps() {
		return this.gps;
	}

	public void setGps(String gps) {
		this.gps = gps;
	}

	@Column(name = "location_name", nullable = false, length = 2000)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

}
